=== Adityaaaaaaaaaaaaaaa/Web/XSD/deleteProfile.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="container" type="containerType"/>
	<xs:complexType name="infoType">
		<xs:sequence>
			<xs:element type="xs:string" name="heading1"/>
			<xs:element type="xs:string" name="heading5"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id"/>
	</xs:complexType>
	<xs:complexType name="label1Type">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element type="xs:string" name="para"/>
			<xs:element type="xs:string" name="br"/>
		</xs:choice>
		<xs:attribute type="xs:string" name="class"/>
	</xs:complexType>
	<xs:complexType name="labelType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="for"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="inputType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="type"/>
				<xs:attribute type="xs:string" name="name"/>
				<xs:attribute type="xs:string" name="id"/>
				<xs:attribute type="xs:string" name="onblur"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="divType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="id"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="label2Type" mixed="true">
		<xs:sequence>
			<xs:element type="labelType" name="label" minOccurs="0"/>
			<xs:element type="xs:string" name="br" minOccurs="0"/>
			<xs:element type="inputType" name="input" minOccurs="0"/>
			<xs:element type="divType" name="div" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id" use="optional"/>
		<xs:attribute type="xs:string" name="class" use="optional"/>
	</xs:complexType>
	<xs:complexType name="aType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="href"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="buttonType">
		<xs:sequence>
			<xs:element type="aType" name="a"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id"/>
		<xs:attribute type="xs:string" name="disabled"/>
	</xs:complexType>
	<xs:complexType name="buttonDivType">
		<xs:sequence>
			<xs:element type="buttonType" name="button"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id"/>
	</xs:complexType>
	<xs:complexType name="formdivType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element type="label1Type" name="label1"/>
			<xs:element type="xs:string" name="br" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element type="label2Type" name="label2"/>
			<xs:element type="buttonDivType" name="buttonDiv"/>
		</xs:choice>
		<xs:attribute type="xs:string" name="id"/>
	</xs:complexType>
	<xs:complexType name="formType">
		<xs:sequence>
			<xs:element type="formdivType" name="formdiv"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="name"/>
		<xs:attribute type="xs:string" name="method"/>
		<xs:attribute type="xs:string" name="action"/>
	</xs:complexType>
	<xs:complexType name="containerType">
		<xs:sequence>
			<xs:element type="infoType" name="info"/>
			<xs:element type="xs:string" name="br"/>
			<xs:element type="formType" name="form"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id"/>
		<xs:attribute type="xs:string" name="class"/>
	</xs:complexType>
</xs:schema>

=== Adityaaaaaaaaaaaaaaa/Web/XML/deleteProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<container id="container" class="fade-in" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/deleteProfile.xsd">

    <info id="infoMsg">
        <heading1>~ Delete Your Profile Information ?~</heading1>
        <heading5>Leaving us ... &#128579; ?</heading5>
    </info><br/>

    <form name="delProfile" method="POST" action="../PHP/profileDelete.php">
        <formdiv id="form1">
            <label1 class="divlabel2">
                <para>Deleting your account will remove all your data from our system</para><br/>
                <para>This action cannot be undone !</para><br/><br/>
                <para>Note: You will be logged out upon deletion</para><br/>
                <para>Please re-enter your password :</para><br/>
            </label1><br/><br/>

            <label2 id="passwordDisplay" class="divlabel">
                <label for="password1">Enter Password</label><br/>
                <input type="password" name="delPwd" id="passwordField" onblur="ajaxPwd()" />
                <div id="delbtn"></div>
            </label2><br/><br/>

            <buttonDiv id="buttonX">
                <button id="nox" disabled="true"><a href="../Webpages/profile.php">Cancel</a></button>
            </buttonDiv>
        </formdiv>
    </form>
</container>
