=== Adityaaaaaaaaaaaaaaa/Web/XSD/Gallery.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="a">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="href" use="optional"/>
					<xs:attribute type="xs:string" name="id" use="optional"/>
					<xs:attribute type="xs:string" name="target" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="text">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="a" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute type="xs:string" name="class" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="img">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="class" use="optional"/>
					<xs:attribute type="xs:string" name="src" use="optional"/>
					<xs:attribute type="xs:string" name="alt" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="middle">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="text"/>
			</xs:sequence>
			<xs:attribute type="xs:string" name="class" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="imgbox">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="img"/>
				<xs:element ref="middle"/>
			</xs:sequence>
			<xs:attribute type="xs:string" name="id" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="bigbox">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="imgbox" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute type="xs:string" name="class"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="imgcontainer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bigbox"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Adityaaaaaaaaaaaaaaa/Web/XML/WallArt.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/NatureLandscape.xslt"?>
<imgcontainer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/Gallery.xsd">
    <bigbox class="bigbox">
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/20230219_212754.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/20230219_212754.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/birmingham-museums-trust-9pOXS0ZGPDM-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/birmingham-museums-trust-9pOXS0ZGPDM-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023 (2).jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023 (2).jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023 (3).jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023 (3).jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-02.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-02.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-03.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-03.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-05.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-05.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-06.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-06.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-09.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Wall arts/copyR@AD_AdobeLr_19_02_2023-09.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
    </bigbox>
</imgcontainer>

=== Adityaaaaaaaaaaaaaaa/Web/XML/NatureLandscape.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/NatureLandscape.xslt"?>
<imgcontainer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/Gallery.xsd">
    <bigbox class="bigbox">
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/silas-baisch-Wn4ulyzVoD4-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/silas-baisch-Wn4ulyzVoD4-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy" >buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/tim-marshall-jqj2SqvxMVY-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/tim-marshall-jqj2SqvxMVY-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/pexels-francesco-ungaro-2325446 (1).jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/pexels-francesco-ungaro-2325446 (1).jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy" >buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/ryan-schroeder-Gg7uKdHFb_c-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/ryan-schroeder-Gg7uKdHFb_c-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy" >buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/john-mark-arnold-XNIjmb6Ax04-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/john-mark-arnold-XNIjmb6Ax04-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy" >buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/marita-kavelashvili-ugnrXk1129g-unsplash (1).jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/marita-kavelashvili-ugnrXk1129g-unsplash (1).jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy" >buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/michael-DXQB5D1njMY-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/michael-DXQB5D1njMY-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy" >buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/PSX_20210222_201738-01.jpeg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/PSX_20210222_201738-01.jpeg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy" >buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Nature-landscape/johann-juraver-2CEkiJSEAFA-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Nature-landscape/johann-juraver-2CEkiJSEAFA-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy" >buy</a>
                </text>
            </middle>
        </imgbox>
    </bigbox>
</imgcontainer>

=== Adityaaaaaaaaaaaaaaa/Web/XML/stilllife.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/NatureLandscape.xslt"?>
<imgcontainer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/Gallery.xsd">
    <bigbox class="bigbox">
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/20210711_123406.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/20210711_123406.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/20210730_174857 (1).jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/20210730_174857 (1).jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/20210918_212544.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/20210918_212544.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/20210929_120637 (1).jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/20210929_120637 (1).jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/20220119_102843.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/20220119_102843.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/20230131_205736.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/20230131_205736.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/aditya-doula-1O56gmrEQzo-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/aditya-doula-1O56gmrEQzo-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/aditya-doula-Cd9kNW2eBkA-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/aditya-doula-Cd9kNW2eBkA-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
        <imgbox id="imgbox">
            <img class="img" src="../Images/Still life/aditya-doula-JdxOJRlgomo-unsplash.jpg" alt=''/>
            <middle class="middle">
                <text class="text">
                    <a href="../Webpages/Reservationform.php">Reserve</a>
                    <a href="../Webpages/Login.php" id="login">login to buy!</a>
                    <a href="../Images/Still life/aditya-doula-JdxOJRlgomo-unsplash.jpg" target="_self" id="view">View</a>
                    <a href="../Webpages/Buy.php" id="Buy">buy</a>
                </text>
            </middle>
        </imgbox>
    </bigbox>
</imgcontainer>
