=== Adityaaaaaaaaaaaaaaa/Web/XSD/xxxlogin.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="loginform">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mainForm-box">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="div" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="switchbut" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="type" use="optional"/>
														<xs:attribute type="xs:string" name="class" use="optional"/>
														<xs:attribute type="xs:string" name="onclick" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="form" minOccurs="0">
											<xs:complexType>
												<xs:choice maxOccurs="unbounded" minOccurs="0">
													<xs:element type="xs:string" name="h1"/>
													<xs:element name="input">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="type" use="optional"/>
																	<xs:attribute type="xs:string" name="class" use="optional"/>
																	<xs:attribute type="xs:string" name="name" use="optional"/>
																	<xs:attribute type="xs:string" name="placeholder" use="optional"/>
																	<xs:attribute type="xs:string" name="onblur" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="div">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="id" use="optional"/>
																	<xs:attribute type="xs:string" name="type" use="optional"/>
																	<xs:attribute type="xs:string" name="class" use="optional"/>
																	<xs:attribute type="xs:string" name="name" use="optional"/>
																	<xs:attribute type="xs:string" name="placeholder" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="button">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="type" use="optional"/>
																	<xs:attribute type="xs:string" name="name" use="optional"/>
																	<xs:attribute type="xs:string" name="class" use="optional"/>
																	<xs:attribute type="xs:string" name="onclick" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:choice>
												<xs:attribute type="xs:string" name="id" use="optional"/>
												<xs:attribute type="xs:string" name="name" use="optional"/>
												<xs:attribute type="xs:string" name="class" use="optional"/>
												<xs:attribute type="xs:string" name="method" use="optional"/>
												<xs:attribute type="xs:string" name="action" use="optional"/>
												<xs:attribute type="xs:string" name="onsubmit" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="class"/>
						<xs:attribute type="xs:string" name="id"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="class"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Adityaaaaaaaaaaaaaaa/Web/XML/xxxlogin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSD/login.xsl"?>
<loginform class="loginform fade-in" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/xxxlogin.xsd">
    <mainForm-box class="mainForm-box" id="FormBox-id">
        <div>
            <switchbut type="button" class="switchbut" onclick="login()">Login</switchbut>
            <switchbut type="button" class="switchbut" onclick="register()">Register</switchbut>
        </div>
        <div>
            <form id="f-login" name="loginForm" class="log-f" method="post" action="../PHP/checkLogin.php">
                <h1>LOG IN</h1>
                <input type="text" class="input-box" name="mLogUname" placeholder="Enter Username" onblur="ajaxLogin()" />
                <div id="loginMsg"></div>
                <input type="password" class="input-box" name="mLogPwd" placeholder="Enter Password" />
                <button type="submit" name="submitLog" class="SubBtn">Login Now</button>
                <button type="button" class="backBtn" onclick="goBack()">Back</button>
            </form>
        </div>
        <div>
            <form id="f-regis" name="registerForm" class="Reg-f" method="post" action="../PHP/checkRegis.php" onsubmit="return checkformRg(this)">
                <h1>Register</h1>
                <input type="text" class="input-box" name="mRegFname" placeholder="Enter your first name"/>
                <input type="text" class="input-box" name="mRegLname" placeholder="Enter your last name"/>
                <input type="text" class="input-box" name="mRegUname" placeholder="Create a Username" onblur="ajaxRegister()" />
                <div id="registerMsg"></div>
                <input type="email" class="input-box" name="mRegEmail" placeholder="Enter your Email here"/>
                <input type="phone" class="input-box" name="mRegPhone" placeholder="Enter your Phone number here"/>
                <input type="password" class="input-box" name="mRegPwd" placeholder="Create a Password" />
                <button type="submit" name="submitReg" class="SubBtn">Register</button>
                <button type="button" class="backBtn" onclick="goBack()">Back</button>
            </form>
        </div>
    </mainForm-box>
</loginform>
